(() => {
  'use strict';
  const root=document.querySelector('[data-v7-calculator]');
  if(!root||!window.PlutusCalcCore)return;
  const ids=['currency','rooms','days','adr','variableCost','fixedCost','currentOccupancy','targetProfit','ancillaryRevenue','otaShare','otaCommission','paymentFee'];
  const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  const out={occupancy:document.getElementById('breakEvenOccupancy'),narrative:document.getElementById('breakEvenNarrative'),nights:document.getElementById('breakEvenNights'),contribution:document.getElementById('contribution'),profit:document.getElementById('projectedProfit'),target:document.getElementById('targetOccupancy'),meter:document.getElementById('breakEvenMeter'),error:document.getElementById('calcError'),chart:document.getElementById('breakEvenChart')};
  const symbol=c=>({EUR:'€',GBP:'£',USD:'$',CAD:'$',AUD:'$',CHF:'CHF ',RON:'RON '}[c]||`${c} `);
  const money=v=>Number.isFinite(v)?`${symbol(el.currency.value)}${new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v)}`:'-';
  const number=(v,d=0)=>Number.isFinite(v)?new Intl.NumberFormat(undefined,{maximumFractionDigits:d}).format(v):'-';
  const pct=v=>Number.isFinite(v)?`${number(v,1)}%`:'-';
  const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
  const read=()=>Object.fromEntries(ids.map(id=>[id,el[id]?.value??'']));
  function clear(){out.occupancy.textContent='-';out.narrative.textContent='Enter the five core numbers to calculate.';out.nights.textContent='-';out.contribution.textContent='-';out.profit.textContent='-';out.target.textContent='-';out.meter.style.width='0%';out.chart.innerHTML='';}
  function draw(m){const svg=out.chart,W=620,H=300,L=58,R=18,T=18,B=36,PW=W-L-R,PH=H-T-B,max=Math.max(...m.graph.flatMap(d=>[d.revenue,d.cost]),1)*1.08,x=o=>L+(o/100)*PW,y=v=>T+PH-(v/max)*PH,path=k=>m.graph.map((d,i)=>`${i?'L':'M'}${x(d.occ).toFixed(1)},${y(d[k]).toFixed(1)}`).join(' ');const grid=[0,.25,.5,.75,1].map(r=>{const yy=y(max*r);return `<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="v7-grid-line"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="v7-chart-text">${Math.round(max*r/1000)}k</text>`}).join(''),xs=[0,25,50,75,100].map(o=>`<text x="${x(o)}" y="${H-10}" text-anchor="middle" class="v7-chart-text">${o}%</text>`).join(''),marker=m.beOcc<=100?`<line x1="${x(m.beOcc)}" y1="${T}" x2="${x(m.beOcc)}" y2="${H-B}" class="v7-marker"/><circle cx="${x(m.beOcc)}" cy="${y(m.beNights*m.revenuePerRoom)}" r="6" fill="#d2b47a"/>`:'';svg.innerHTML=`${grid}${xs}<path d="${path('revenue')}" class="v7-revenue-line"/><path d="${path('cost')}" class="v7-cost-line"/>${marker}`;}
  function update(){const m=window.PlutusCalcCore.calculate(read());if(!m.valid){out.error.style.display='block';out.error.textContent=m.errors[0];clear();return;}out.error.style.display='none';out.occupancy.textContent=pct(m.beOcc);out.nights.textContent=number(m.beNights,0);out.contribution.textContent=money(m.contribution);out.profit.textContent=m.currentProfit===null?'Add occupancy':money(m.currentProfit);out.target.textContent=m.targetOcc===null?'Add target':pct(m.targetOcc);out.meter.style.width=`${clamp(m.beOcc,0,100)}%`;out.narrative.textContent=m.beOcc>100?'Break-even is above available capacity with these assumptions.':`About ${number(m.beNights,0)} occupied room nights are needed in this period.`;draw(m);}
  ids.forEach(id=>{el[id]?.addEventListener('input',update);el[id]?.addEventListener('change',update);});clear();
})();