(()=>{
'use strict';
const addStyle=(href)=>{if(!document.querySelector(`link[href^="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href+'?v=20260903';document.head.appendChild(l)}};
addStyle('v15.css');addStyle('v16.css');addStyle('v17.css');addStyle('v17-articles.css');addStyle('v18.css');
if(!document.querySelector('script[src^="v17.js"]')){const s=document.createElement('script');s.src='v17.js?v=20260903';s.defer=true;document.head.appendChild(s)}
const header=document.querySelector('[data-v10-header]');
const footer=document.querySelector('[data-v10-footer]');
if(header){header.innerHTML=`<header class="v15-header"><div class="v15-nav">
<a class="v15-brand" href="index.html"><img src="logo/plutus-mark-v15.svg" alt="Plutus Hotel Revenue"><span><b>PLUTUS</b><i>HOTEL REVENUE</i></span></a>
<nav class="v15-links" aria-label="Main navigation"><a href="index.html">Home</a><a href="about.html">About</a><a href="revenue_management.html">Revenue</a><div class="v15-group"><button type="button">Software</button><div class="v15-drop"><a href="software.html">Overview</a><a href="mews_pms.html">Mews</a><a href="cloudbeds_pms.html">Cloudbeds</a><a href="siteminder_chm.html">SiteMinder</a></div></div><div class="v15-group"><button type="button">Tips</button><div class="v15-drop"><a href="tips.html">All guides</a><a href="hotel_photoshoot_tips.html">Photography</a><a href="web_design_tips.html">Hotel website</a><a href="digital_marketing_tips.html">Digital marketing</a><a href="hotel-break-even-calculator.html">Break-even</a></div></div><a href="blog.html">Notes</a></nav>
<a class="v15-contact" href="contact.html">Discuss your hotel <span>↗</span></a><button class="v15-menu" type="button" aria-expanded="false"><span></span><span></span></button></div><div class="v15-progress"><i></i></div></header><div class="v15-mobile-panel"><a href="index.html">Home</a><a href="about.html">About</a><a href="revenue_management.html">Revenue</a><a href="software.html">Software</a><a href="tips.html">Tips & tools</a><a href="blog.html">Notes</a><a href="contact.html">Contact</a></div>`;
const menu=header.querySelector('.v15-menu');menu?.addEventListener('click',()=>{document.body.classList.toggle('v15-nav-open');menu.setAttribute('aria-expanded',String(document.body.classList.contains('v15-nav-open')))});
header.querySelectorAll('.v15-group>button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const group=btn.parentElement;header.querySelectorAll('.v15-group').forEach(x=>x!==group&&x.classList.remove('open'));group.classList.toggle('open')}));
document.addEventListener('click',e=>{if(!e.target.closest('.v15-group'))header.querySelectorAll('.v15-group').forEach(x=>x.classList.remove('open'))});
}
if(footer){footer.innerHTML=`<footer class="v15-footer"><div class="v15-footer-main"><div class="v15-footer-brand"><img src="logo/plutus-mark-v15.svg" alt="Plutus"><h2>Better commercial decisions.<br>One hotel at a time.</h2><div class="v18-social-footer"><a href="https://www.linkedin.com/in/norbertnica/" target="_blank" rel="noopener noreferrer">Personal LinkedIn</a><a href="https://www.linkedin.com/company/plutushotelrevenue/" target="_blank" rel="noopener noreferrer">Plutus LinkedIn</a><a href="https://www.facebook.com/plutushotelrevenue/" target="_blank" rel="noopener noreferrer">Facebook</a></div></div><div class="v15-footer-links"><div><b>PLUTUS</b><a href="about.html">About</a><a href="revenue_management.html">Revenue</a><a href="contact.html">Contact</a></div><div><b>EXPLORE</b><a href="software.html">Software</a><a href="tips.html">Tips & tools</a><a href="blog.html">Notes</a></div><div><b>LEGAL</b><a href="privacy_policy.html">Privacy</a><a href="terms_and_conditions.html">Terms</a></div></div></div><div class="v15-footer-bottom"><span>© ${new Date().getFullYear()} Plutus Hotel Revenue</span><span>Independent revenue management / Barcelona</span></div></footer>`}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-in');revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('[data-reveal]').forEach(el=>{el.classList.add('v15-reveal');revealObserver.observe(el)});
const progress=document.querySelector('.v15-progress i');const updateProgress=()=>{if(!progress)return;const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`};addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const hero=document.querySelector('.home-hero'),sculpture=document.querySelector('.signal-sculpture');if(hero&&sculpture&&!matchMedia('(prefers-reduced-motion: reduce)').matches){hero.addEventListener('pointermove',e=>{const r=sculpture.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;sculpture.style.transform=`rotateY(${x*2.2}deg) rotateX(${-y*1.6}deg)`;sculpture.querySelectorAll('.signal-plane').forEach((p,i)=>{p.style.translate=`${x*(i+1)*12}px ${y*(i+1)*8}px`});sculpture.querySelectorAll('.signal-float').forEach((p,i)=>{p.style.translate=`${x*(i?15:-13)}px ${y*(i?10:-8)}px`})});hero.addEventListener('pointerleave',()=>{sculpture.style.transform='';sculpture.querySelectorAll('.signal-plane,.signal-float').forEach(p=>p.style.translate='0 0')})}
const parallax=[...document.querySelectorAll('[data-parallax]')];if(parallax.length&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let ticking=false;const paint=()=>{parallax.forEach(el=>{const r=el.getBoundingClientRect();const d=(r.top+0.5*r.height-innerHeight/2)/innerHeight;el.style.setProperty('--parallax',`${Math.max(-1,Math.min(1,d))*-28}px`)});ticking=false};addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(paint);ticking=true}},{passive:true});paint()}
})();
