(()=>{
'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const hs=[...document.querySelectorAll('[data-hscroll]')];
if(hs.length&&!reduce){let ticking=false;const paint=()=>{hs.forEach(sec=>{const track=sec.querySelector('.home19-track');if(!track)return;const r=sec.getBoundingClientRect();const travel=Math.max(1,sec.offsetHeight-innerHeight);const p=clamp(-r.top/travel,0,1);const panels=track.children.length;track.style.transform=`translate3d(${-p*(panels-1)*100}vw,0,0)`});ticking=false};addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(paint);ticking=true}},{passive:true});paint()}
const scan=document.querySelector('[data-scan]');if(scan&&!reduce){let ticking=false;const paint=()=>{const r=scan.getBoundingClientRect();const travel=Math.max(1,scan.offsetHeight-innerHeight);const p=clamp(-r.top/travel,0,1);scan.style.setProperty('--scan',p.toFixed(4));const n=scan.querySelector('[data-scan-number]');if(n)n.textContent=String(Math.min(5,Math.floor(p*5)+1)).padStart(2,'0');ticking=false};addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(paint);ticking=true}},{passive:true});paint()}
const cards=[...document.querySelectorAll('.software15-card')];if(cards.length&&!reduce){cards.forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`translate3d(${x*8}px,${y*8}px,0) rotateX(${-y*4}deg) rotateY(${x*5}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
const portals=[...document.querySelectorAll('.tips19-world,.home19-portal')];if(portals.length&&!reduce){portals.forEach(p=>p.addEventListener('pointermove',e=>{const img=p.querySelector('img');if(!img)return;const r=p.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;img.style.transform=`scale(1.035) translate(${x*-10}px,${y*-8}px)`}));portals.forEach(p=>p.addEventListener('pointerleave',()=>{const img=p.querySelector('img');if(img)img.style.transform=''}))}
const acts=[...document.querySelectorAll('.rev19-act')];if(acts.length){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.rev19-index a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-35% 0px -50% 0px'});acts.forEach(a=>obs.observe(a))}
if(!reduce){document.querySelectorAll('.marketing19-ring').forEach((ring,i)=>ring.animate([{transform:'rotate(0deg)'},{transform:`rotate(${i%2?'-360deg':'360deg'})`}],{duration:22000+i*6500,iterations:Infinity,easing:'linear'}));}
})();